### ISSUE TITLE
[QoL/Config] Disable mod for teleporter items

### ISSUE THREAD

**Issue by DaltonGoesFast** [Cercain/ImprovedCommandEssence#15] opened 2023-06-21 17:58 UTC
A config would be nice to make it so that this mod doesn't affect boss/tp drops.

This would be to address an incompatibility with BetterBossLootDropping by FakeMods. When ICE is on, the tp items will still spawn out of the tp pad if any of them roll a command drop. When command is off, BBLD makes its so TP items go directly into the players inventory. If a  direct compatibility solution would be easy that would be great but i think just making a toggle to affect tp items would do the trick

thank you :)

**Comment by Cercain** [comment] 2024-05-16 08:32
Hi, sorry for such a late response here.

It looks like this is a compatibility issue with using vanilla Command.
I will look into a solution, but even when I don't hook into the Boss Drop event, vanilla Command overrides BBLD, something like that would be better handled by their own mod.

(I'll try a few things but will close this if I'm unable to find a solution as the issue is with BBLD)

**Closed as not planned** 2024-05-24 18:31 UTC
Labels: Compatability
